### PR TITLE
Updating to fix the simdjson and jsonifier build flags.

### PR DESCRIPTION
**Pull request by NotAnotherGayDude**
It seems that passing the NDEBUG, 03, and release flags are required for simdjson to build properly.

### CODE REVIEW

**Comment by Loki-Astari** [comment]
@RealTimeChris and @stephenberry Pulling you in to this conversation as you are the maintainer of Jsonifier/Glaze

Any objects to this change? They look good to me.

**Comment by RealTimeChris** [comment]
Looks good to me.

**Comment by NotAnotherGayDude** [comment]
> NDEBUG will be automatically defined when building in release. It shouldn't have to be passed in. I'd also be surprised if O3 is required for simdjson to perform. O2 should be good, but O3 might get a bit better performance out of most libraries.

I know this but given the response over @ https://github.com/simdjson/simdjson/discussions/2281#discussioncomment-11036765, I figured I would make this PR.

**Comment by Loki-Astari** [comment]
I'll give it a try.
I'll rollback if there are any changes in the Conformance tests.

**Comment by Loki-Astari** [comment]
All conformance test are the same (as expected)

Jsonifier picked up speed in one test.  
SimdJson had a couple of test increase in speed very slightly.  
## Jsonifier

| Library | 1. Parse Time (ms) | 1. Parse Memory (byte) | 1. Parse MemoryPeak (byte) | 1. Parse AllocCount | 1. Parse LeakedBytes | 1. Parse LeakCount | 2. Stringify Time (ms) | 2. Stringify LeakedBytes | 2. Stringify LeakCount | 3. Prettify Time (ms) | 3. Prettify LeakedBytes | 3. Prettify LeakCount | 5. SaxRoundtrip Time (ms) | 5. SaxRoundtrip LeakedBytes | 5. SaxRoundtrip LeakCount | 7. Code size FileSize (byte) |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| Darwin Before | 5 | 3,870,824 | 3,950,280 | 123,936 | 0 | 0 | 3 | 0 | 0 | 5 | 0 | 0 | 9 | 0 | 0 |
| Darwin After  | 5 | 3,870,824 | 3,950,280 | 123,936 | 0 | 0 | 3 | 0 | 0 | 4 | 0 | 0 | 8 | 0 | 0 |
| Linux Before | 8 | 3,926,653 | 4,006,109 | 124,649 | 0 | 0 | 5 | 0 | 0 | 7 | 0 | 0 | 13 | 0 | 0 |
| Linux After | 8 | 3,926,653 | 4,006,109 | 124,649 | 0 | 0 | 5 | 0 | 0 | 7 | 0 | 0 | 13 | 0 | 0 |


## SimdJson
| Library | 1. Parse Time (ms) | 1. Parse Memory (byte) | 1. Parse MemoryPeak (byte) | 1. Parse AllocCount | 1. Parse LeakedBytes | 1. Parse LeakCount | 2. Stringify Time (ms) | 2. Stringify LeakedBytes | 2. Stringify LeakCount | 3. Prettify Time (ms) | 3. Prettify LeakedBytes | 3. Prettify LeakCount | 5. SaxRoundtrip Time (ms) | 5. SaxRoundtrip LeakedBytes | 5. SaxRoundtrip LeakCount | 7. Code size FileSize (byte) |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| Darwin Before Demand | 8 | 4,610,201 | 8,490,817 | 122,597 | 0 | 0 | 63 | 0 | 0 | 63 | 0 | 0 | 68 | 0 | 0 |
| Darwin After Demand  | 7 | 4,610,201 | 8,490,817 | 122,597 | 0 | 0 | 59 | 0 | 0 | 60 | 0 | 0 | 68 | 0 | 0 |
| Darwin Before Dom | 7 | 3,801,896 | 8,491,201 | 122,597 | 0 | 0 | 52 | 0 | 0 | 54 | 0 | 0 | 61 | 0 | 0 |  
| Darwin After DOM | 7 | 3,801,896 | 8,491,201 | 122,597 | 0 | 0 | 53 | 0 | 0 | 49 | 0 | 0 | 56 | 0 | 0 |  
| Linux Before Demand | 9 | 4,610,201 | 8,553,430 | 123,112 | 0 | 0 | 66 | 0 | 0 | 65 | 0 | 0 | 75 | 0 | 0 |  
| Linux Afer Demand  | 9 | 4,610,201 | 8,553,430 | 123,112 | 0 | 0 | 66 | 0 | 0 | 65 | 0 | 0 | 75 | 0 | 0 |  
| Linux Before Dom | 10 | 3,863,777 | 8,553,974 | 123,112 | 0 | 0 | 61 | 0 | 0 | 61 | 0 | 0 | 71 | 0 | 0 |
| Linux After Dom  | 10 | 3,863,777 | 8,553,974 | 123,112 | 0 | 0 | 61 | 0 | 0 | 61 | 0 | 0 | 71 | 0 | 0

**Comment by NotAnotherGayDude** [comment]
> All conformance test are the same (as expected)
> 
> Jsonifier picked up speed in one test. SimdJson had a couple of test increase in speed on the Prettify.
> 
> ## Jsonifier
> Library	1. Parse Time (ms)	1. Parse Memory (byte)	1. Parse MemoryPeak (byte)	1. Parse AllocCount	1. Parse LeakedBytes	1. Parse LeakCount	2. Stringify Time (ms)	2. Stringify LeakedBytes	2. Stringify LeakCount	3. Prettify Time (ms)	3. Prettify LeakedBytes	3. Prettify LeakCount	5. SaxRoundtrip Time (ms)	5. SaxRoundtrip LeakedBytes	5. SaxRoundtrip LeakCount	7. Code size FileSize (byte)
> Darwin Before	5	3,870,824	3,950,280	123,936	0	0	3	0	0	5	0	0	9	0	0	
> Darwin After	5	3,870,824	3,950,280	123,936	0	0	3	0	0	4	0	0	8	0	0	
> Linux Before	8	3,926,653	4,006,109	124,649	0	0	5	0	0	7	0	0	13	0	0	
> Linux After	8	3,926,653	4,006,109	124,649	0	0	5	0	0	7	0	0	13	0	0	
> ## SimdJson
> Library	1. Parse Time (ms)	1. Parse Memory (byte)	1. Parse MemoryPeak (byte)	1. Parse AllocCount	1. Parse LeakedBytes	1. Parse LeakCount	2. Stringify Time (ms)	2. Stringify LeakedBytes	2. Stringify LeakCount	3. Prettify Time (ms)	3. Prettify LeakedBytes	3. Prettify LeakCount	5. SaxRoundtrip Time (ms)	5. SaxRoundtrip LeakedBytes	5. SaxRoundtrip LeakCount	7. Code size FileSize (byte)
> Darwin Before Demand	8	4,610,201	8,490,817	122,597	0	0	63	0	0	63	0	0	68	0	0	
> Darwin After Demand	7	4,610,201	8,490,817	122,597	0	0	59	0	0	60	0	0	68	0	0	
> Darwin Before Dom	7	3,801,896	8,491,201	122,597	0	0	52	0	0	54	0	0	61	0	0	 
> Darwin After DOM	7	3,801,896	8,491,201	122,597	0	0	53	0	0	49	0	0	56	0	0	 
> Linux Before Demand	9	4,610,201	8,553,430	123,112	0	0	66	0	0	65	0	0	75	0	0	 
> Linux Afer Demand	9	4,610,201	8,553,430	123,112	0	0	66	0	0	65	0	0	75	0	0	 
> Linux Before Dom	10	3,863,777	8,553,974	123,112	0	0	61	0	0	61	0	0	71	0	0	
> Linux After Dom	10	3,863,777	8,553,974	123,112	0	0	61	0	0	61	0	0	71	0	0

Awesome thanks!

**Pull request merged**
