### PR TITLE
Simplify Glaze meta and avoid potential buffer copies

### PR DESCRIPTION
**Pull request by stephenberry**
I haven't been able to build your test code (so there may be a minor typo here). But, I've updated the Glaze code to have simpler meta registration and avoid potential string copies. RVO doesn't always apply when converting from the contents of an `expected` to its destination. This change avoids compilers potentially generating a copy of the output buffer. It is also simpler and cleaner.

### CODE REVIEW

**Comment by Loki-Astari** [comment]
I'll try and test tonight.

**Comment by RealTimeChris** [comment]
> I haven't been able to build your test code (so there may be a minor typo here). But, I've updated the Glaze code to have simpler meta registration and avoid potential string copies. RVO doesn't always apply when converting from the contents of an `expected` to its destination. This change avoids compilers potentially generating a copy of the output buffer. It is also simpler and cleaner.

If you enable actions on your fork of the repo you can see if it builds there.

**Comment by Loki-Astari** [comment]
Does not look like it builds:
https://github.com/stephenberry/JsonBenchmark/actions/runs/11126130212/job/30915358590

**Comment by Loki-Astari** [comment]
Mote than happy to get on a zoom call to try and get your local mac building running.

**Comment by Loki-Astari** [comment]
Problems seems to be this:
````
  229 template <typename T> struct glz::meta<Glaze::GetValueResult<T>> {
  230   using T = Glaze::GetValueResult<T>;
  231   static constexpr auto value = object(&T::data);
  232 };
````

**Comment by Loki-Astari** [comment]
Conformance is the same.
Performance changes:

````
New Time on left: Old Times on right
1. Parse,Glaze,canada.json,4.51069,2868728,2948152,114194,0,0 |	1. Parse,Glaze,canada.json,4.52389,2868728,2948152,114194,0,0
2. Stringify,Glaze,canada.json,2.46505,2129952,3194912,14,0,0 |	2. Stringify,Glaze,canada.json,2.73563,2090272,4220192,15,0,0
3. Prettify,Glaze,canada.json,3.70655,8519712,12779552,16,0,0 |	3. Prettify,Glaze,canada.json,4.62581,6661936,15181616,17,0,0
5. SaxRoundtrip,Glaze,canada.json,7.01468,2129952,6063640,114 |	5. SaxRoundtrip,Glaze,canada.json,7.89906,2090272,7088920,114
1. Parse,Glaze,twitter.json,0.494254,490432,490432,3034,0,0,0 |	1. Parse,Glaze,twitter.json,0.490375,490432,490432,3034,0,0,0
2. Stringify,Glaze,twitter.json,0.137517,532512,798752,12,0,0 |	2. Stringify,Glaze,twitter.json,0.147483,424776,957256,13,0,0
3. Prettify,Glaze,twitter.json,0.272829,1064992,1597472,13,0, |	3. Prettify,Glaze,twitter.json,0.286687,632040,1697000,14,0,0
5. SaxRoundtrip,Glaze,twitter.json,0.665634,532512,1289184,30 |	5. SaxRoundtrip,Glaze,twitter.json,0.720442,424776,1447688,30
1. Parse,Glaze,citm_catalog.json,0.959613,554104,554136,7422, |	1. Parse,Glaze,citm_catalog.json,0.920175,554104,554136,7422,
2. Stringify,Glaze,citm_catalog.json,0.257775,532512,798752,1 |	2. Stringify,Glaze,citm_catalog.json,0.258954,479920,1012400,
3. Prettify,Glaze,citm_catalog.json,0.653496,2129952,3194912, |	3. Prettify,Glaze,citm_catalog.json,0.722575,1405312,3535232,
5. SaxRoundtrip,Glaze,citm_catalog.json,1.20249,532512,135285 |	5. SaxRoundtrip,Glaze,citm_catalog.json,1.1804,479920,1566504

**Comment by Loki-Astari** [comment]
I have add the fix I mentioned above.
Merged this and all the code into master.
Closing this merge request.

**Comment by Loki-Astari** [comment]
````
commit d9443f7178ee4b1a6635b641cc7216091476a9f6 (HEAD -> master, origin/master, origin/HEAD)
Merge: 0be292b ac7f3cb
Author: Loki Astari <Loki.Astari@gmail.com>
Date:   Tue Oct 1 11:12:53 2024 -0700

    Merge branch 'simplify_glaze'

commit ac7f3cb87ea3142c6f0f364d5da2f9c0b8a56283 (origin/simplify_glaze, simplify_glaze)
Author: Loki Astari <Loki.Astari@gmail.com>
Date:   Tue Oct 1 11:12:04 2024 -0700

    Fix Minor syntax error

commit 4066a6a08dad6effe9223d7e864c9fccc4ccf11a
Author: Stephen Berry <stephenberry.developer@gmail.com>
Date:   Tue Oct 1 08:29:50 2024 -0500

    Added missing semi-colon

commit b58203fb2ff09a1358d2bc36ccc6a2ecd79017ac
Author: Stephen Berry <stephenberry.developer@gmail.com>
Date:   Mon Sep 30 15:28:40 2024 -0500

    Simplify Glaze meta and avoid potential buffer copies
````

**Comment by stephenberry** [comment]
Thanks!

**Pull request closed without merging**
